### ISSUE TITLE
Build CicadaPlayer for both Simulator and Device

### ISSUE THREAD

**Issue by isaacroldan** [alibaba/CicadaPlayer#588]
**Describe the bug**
Following the instructions to compile CicadaPlayer for iOS, the result is that the CicadaPlayer only works on an iOS device, can't make it work on a Simulator. 

It says `alivcffmpeg` is only built for arm64, but for what i see in the scripts, it should create Fat frameworks with all architectures right? 

Should `CicadaPlayerSDK.framework` and `alivcffmepg.framework` contain all architectures?

Am I doing something wrong?

Thanks 🙇 

**To Reproduce**
1.  Clone repo
2. Follow README instructions to build for iOS
3. Try to execute CicadaDemo in a Simulator

**Expected behavior**
I can execute CicadaDemo in both Device and Simulator

**Comment by pingkai** [comment]
try clean and rebuild in xcode

**Comment by isaacroldan** [comment]
Yep, already tried that, but doesn't work, can't compile on simulator :/

**Comment by isaacroldan** [comment]
Maybe I have something wrong on my computer, but this is the error i'm getting:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_EAGLContext", referenced from:
      objc-class-ref in librender.a(eagl_context.o)
  "_glIsRenderbuffer", referenced from:
      Cicada::CicadaEAGLContext::DestroySurface(Cicada::GLSurface*&) in librender.a(eagl_context.o)
  "_glGenRenderbuffers", referenced from:
      Cicada::CicadaEAGLContext::CreateSurface() in librender.a(eagl_context.o)
  "_glBindRenderbuffer", referenced from:
      Cicada::CicadaEAGLContext::CreateSurface() in librender.a(eagl_context.o)
      Cicada::CicadaEAGLContext::MakeCurrent(Cicada::GLSurface*) in librender.a(eagl_context.o)

// [...]
// The log is over 600 lines long, this is just a subset, all related to OpenGL and librender.a

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This happens specifically when building `CicadaPlayerSDK.framework`

Doing a `lipo -info librender.a` tells me that this library does have all architectures inside...

This is just after cloning and following the steps in the README.
I'm working with Big Sur and Xcode 12.3 (although i've tested with 11.5 too and same result)

Any idea?
Thanks you 🙇

**Comment by pingkai** [comment]
OK, I've got the reason , wait me fix it :)

**Comment by pingkai** [comment]
https://github.com/alibaba/CicadaPlayer/commit/e02af5beda35f26ae7e88d1f830e55c4e4ccaa08, fixed

**Comment by isaacroldan** [comment]
It works now!! Thanks @pingkai 🙇

**Comment by pingkai** [comment]
Thanks for your issue @isaacroldan
